Custom bitrise step.

diff --git a/step.yml b/step.yml
--- a/step.yml
+++ b/step.yml
@@ -1,58 +1,127 @@
-title: "STEP TEMPLATE"
-summary: A short summary of the step. Don't make it too long ;)
+title: Script
+summary: |-
+  Run any custom script you want. The power is in your hands. Use it wisely!
 description: |-
-  This is a Step template.
-  Contains everything what's required for a valid Stepman managed step.
 
-  A Step's description (and generally any `description` property)
-  can be a [Markdown](https://en.wikipedia.org/wiki/Markdown) formatted text.
+  Run any custom script you want as part of your Bitrise build. All you need to do is specifying the script runner  
+  (the default is bash), add the script, and run a build. 
+  
+  You can also read the script from a file.
 
-  To create your own Step:
+  ### Configuring the Step
 
-  1. Create a new repository on GitHub
-  2. Copy the files from this folder into your repository
-  3. That's all, you can use it on your own machine
-  4. Once you're happy with it you can share it with others.
-website: https://github.com/...
-source_code_url: https://github.com/...
-support_url: https://github.com/.../issues
+  1. Set the **Execute with/runner binary** input.
+
+     Either define the path of the executor, or simply just add its name if you know it is available in the PATH, such as `ruby` or `python`. It can even be a command, such as `go run`.  
+
+  1. Write your script in the **Script content** input or specify a script file.
+
+     If you have a script in your repository, you can simply run it from the file, either by calling it in the **Script content** input  
+     or, optionally, by specifying the path to it in the **Script file path** input. 
+     
+     Be aware that relative paths are relative to the value set in the **Working directory** input - by default, it is your app's source directory.
+
+  ### Troubleshooting
+
+  If the script fails, check the executor first - obviously, a Python script will not work with a bash runner.
+
+  Note that in certain cases, the filename or the filepath actually matters. For example, the `go run` command only accepts `.go` files.
+
+  ### Useful links
+
+  * [System reports to check out the pre-installed executors](https://github.com/bitrise-io/bitrise.io/tree/master/system_reports)
+  * [Exporting to Test Reports from custom Script Steps](https://devcenter.bitrise.io/testing/exporting-to-test-reports-from-custom-script-steps/)
+
+  ### Related Steps
+
+  * [Script Runner](https://www.bitrise.io/integrations/steps/script-runner)
+  * [Remote Bash Script Runner](https://www.bitrise.io/integrations/steps/remote-script-runner)
+website: https://github.com/bitrise-io/steps-script
+source_code_url: https://github.com/bitrise-io/steps-script
+support_url: https://github.com/bitrise-io/steps-script/issues
 host_os_tags:
-  - osx-10.10
-project_type_tags:
-  - ios
-  - android
-  - xamarin
+  - osx
+  - ubuntu
+project_type_tags: []
 type_tags:
-  - script
-is_requires_admin_user: true
+  - utility
+is_requires_admin_user: false
 is_always_run: false
 is_skippable: false
-deps:
-  brew:
-  - name: git
-  - name: wget
-  apt_get:
-  - name: git
-  - name: wget
-run_if: ""
 inputs:
-  - example_step_input: Default Value - you can leave this empty if you want to
-    opts:
-      title: "Example Step Input"
-      summary: Summary. No more than 2-3 sentences.
-      description: |
-        Description of this input.
+  - content: |-
+      #!/usr/bin/env bash
+      # fail if any commands fails
+      set -e
+      # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+      set -o pipefail
+      # debug log
+      set -x
 
-        Can be Markdown formatted text.
-      is_expand: true
+      # write your script here
+      echo "Hello World!"
+
+      # or run a script from your repository, like:
+      # bash ./path/to/script.sh
+      # not just bash, e.g.:
+      # ruby ./path/to/script.rb
+    opts:
+      title: "Script content"
+      description: |
+        Type your script here.
+
+        **Make sure that it returns a non zero exit code in case of an error!**
+        The step will only fail if your script returns with a non zero exit code!
+      is_expand: false
       is_required: true
-      value_options: []
-outputs:
-  - EXAMPLE_STEP_OUTPUT:
+  - runner_bin: "/bin/bash"
     opts:
-      title: "Example Step Output"
-      summary: Summary. No more than 2-3 sentences.
+      category: Config
+      title: "Execute with / runner binary"
       description: |
-        Description of this output.
+        The executor to be used for running the script.
+        If it's available in the PATH you can just
+        specify `ruby` or `python`, generally
+        if you know the path of the executor you should
+        define that, like `/bin/bash`.
 
-        Can be Markdown formatted text.
+        You can even specify an execution command
+        like `go run` instead of just a binary.
+      is_required: true
+  - working_dir: "$BITRISE_SOURCE_DIR"
+    opts:
+      category: Config
+      title: "Working directory"
+      description: |
+        This directory will be set as the current working
+        directory for the script.
+
+        Any relative path in the Script (content) will be
+        relative to this directory.
+  - script_file_path: ""
+    opts:
+      category: Config
+      title: "Script file path"
+      description: |
+        Save the specified script content to this path
+        before execution. The file will be removed after
+        the script finishes.
+
+        Generally you don't have to define this but
+        there might be cases where the file's name or path
+        actually matters.
+        For example `go run` only accepts `.go` files.
+
+        If you specify a relative path then it will be
+        relative to the *working directory* (which you
+        can optionally specify as well).
+  - is_debug: "no"
+    opts:
+      category: Debug
+      title: "Debug print?"
+      description: |
+        If debug=yes the step will print debug infos about
+        the working dir, tmp file path, exit code, etc.
+      value_options:
+        - "no"
+        - "yes"
